# 12. Ejercicio de Manipulación de datos

### Filtrar datos de un dataframe.

    1. Crear una lista de 50 valores aleatorios entre los valores de 0 a 100
    2. Convertir esa lista en un dataframe de 5 filas por 10 columnas
    3. Filtrar los datos del dataframe para visualizar solo los valores mayores de 50

In [3]:
#Importar librerías
import numpy as np
import pandas as pd

# 1. Crear una lista de 50 valores aleatorios entre los valores de 0 a 100
# 2. Convertir esa lista en un dataframe de 5 filas por 10 columnas
# 3. Filtrar los datos del dataframe para visualizar solo los valores mayores de 50


In [4]:
#1. Crear una lista de 50 valores aleatorios entre los valores de 0 a 100
lista = np.random.randint(0, 101, 50)

print(lista)

[ 75  85  33  15  73  27  29  24  82  75  25  68  16  81  90  48  63  15
  37  86   0  63  84  61  88  15  66  85  48  14   0  28  23  37  27  87
  20 100  65   4  91  63   9  69  87  62  68  57  79  82]


In [5]:
#Función reshape no modifica la variable

lista = np.reshape(lista, (5, 10))
print(lista)


[[ 75  85  33  15  73  27  29  24  82  75]
 [ 25  68  16  81  90  48  63  15  37  86]
 [  0  63  84  61  88  15  66  85  48  14]
 [  0  28  23  37  27  87  20 100  65   4]
 [ 91  63   9  69  87  62  68  57  79  82]]


In [6]:
#2. Convertir esa lista en un dataframe de 5 filas por 10 columnas

df = pd.DataFrame(lista)

print(df)

    0   1   2   3   4   5   6    7   8   9
0  75  85  33  15  73  27  29   24  82  75
1  25  68  16  81  90  48  63   15  37  86
2   0  63  84  61  88  15  66   85  48  14
3   0  28  23  37  27  87  20  100  65   4
4  91  63   9  69  87  62  68   57  79  82


In [7]:
#3. Filtrar los datos del dataframe para visualizar solo los valores mayores de 50
df_filtrado = df[df > 50]
print(df_filtrado)


      0     1     2     3     4     5     6      7     8     9
0  75.0  85.0   NaN   NaN  73.0   NaN   NaN    NaN  82.0  75.0
1   NaN  68.0   NaN  81.0  90.0   NaN  63.0    NaN   NaN  86.0
2   NaN  63.0  84.0  61.0  88.0   NaN  66.0   85.0   NaN   NaN
3   NaN   NaN   NaN   NaN   NaN  87.0   NaN  100.0  65.0   NaN
4  91.0  63.0   NaN  69.0  87.0  62.0  68.0   57.0  79.0  82.0


In [8]:
df_final = df_filtrado.fillna(0)
print(df_final)

      0     1     2     3     4     5     6      7     8     9
0  75.0  85.0   0.0   0.0  73.0   0.0   0.0    0.0  82.0  75.0
1   0.0  68.0   0.0  81.0  90.0   0.0  63.0    0.0   0.0  86.0
2   0.0  63.0  84.0  61.0  88.0   0.0  66.0   85.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0  87.0   0.0  100.0  65.0   0.0
4  91.0  63.0   0.0  69.0  87.0  62.0  68.0   57.0  79.0  82.0
