# NB6. Numpy

Numpy es un paquete que provee a Python con arreglos multidimensionales (vectores o matrices) de alta eficiencia y diseñados para cálculo científico.

https://numpy.org/

Para utilizar este módulo es necesario importarlo:

In [1]:
import numpy as np

## 6.1 Funciones básicas de numpy para arreglos

- np.zeros(n)
- np.ones(n)
- np.arange(a, b, i)
- np.array(arreglo)
- np.shape(arreglo)


### 1. En el siguiente código realice lo que se le pide:

In [ ]:
#1. Crear un arreglo que contenga 4 ceros con la función np.zeros(n). Donde n es el tamaño del arreglo e imprimirlo.

import numpy as np

arreglo = np.zeros(4)
print(arreglo)

[0. 0. 0. 0.]


In [2]:
#2. Crear un arreglo que contenga 5 unos con la función np.ones(n). Donde n es el tamaño del arreglo e imprimirlo.

import numpy as np

arreglo_unos = np.ones(5)
print(arreglo_unos)

[1. 1. 1. 1. 1.]


In [3]:
#3. Crear un arreglo que contenga los números del 0 al 9 consecutivos usando la función np.arange(n+1), 
# donde n es el último número del arreglo.

import numpy as np

arreglo = np.arange(10)
print(arreglo)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
#4. Crear un arreglo que contenga la secuencia de los números del 2 al 20, 
# y el incremento entre cada número de la secuencia sea de 3.
# Utilice la función arange(a, b, i), donde a es el inicio de la secuencia, b es el final de la secuencia e i es el incremento.

import numpy as np

arreglo = np.arange(2, 21, 3)
print(arreglo)



[ 2  5  8 11 14 17 20]


In [7]:
#5. Obtenga un arreglo (array) a partir de una lista cualquiera definida por usted utilizando la función np.array(arreglo)
import numpy as np 

lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista) 
print(arreglo)

[1 2 3 4 5]


In [9]:
#6. Obtenga un array doble o matriz a patir de una lista doble
#   Defina la lista doble a partir de dos listas simples: (lista1, lista2)
#   Convierta a matriz utilizando la función np.array(lista_doble)
#   Imprima el resultado

import numpy as np

lista1 = [1,2,3]
lista2 = [4,5,6]
lista_doble = [lista1, lista2]
matriz = np.array(lista_doble) 
print(matriz)


[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [10]:
#7. Imprima las dimensiones de la matriz utilizando la función np.shape(arreglo)
import numpy as np

arreglo = np.array([[1,2,3],[4,5,6]])

print(np.shape(arreglo))

(2, 3)


## 6.2 Operaciones con arrays

A diferencia de las listas, con los arrays sí es posible utilizar los operadores + y * de forma matemática.

### 2. Realice el código que se le pide en cada celda:

In [12]:
#1. Crear dos arrays con valores consecutivos cualesquiera utilizando la función np.arange(), y que sean de tamaño 5.

import numpy as np

array1 = np.arange(5)
array2 = np.arange(5,10)

print(array1)
print(array2)

[0 1 2 3 4]
[5 6 7 8 9]


In [13]:
# 2. Utilizando el operador *, multiplique por una constante uno de los arrays

import numpy as np

constante = 5
array1 = np.arange(5)

resultado = [elemento * constante for elemento in array1]
print(resultado)


[0, 5, 10, 15, 20]


In [14]:
#3. Uitlizando el operador +, sume una constante a uno de los arrays.
import numpy as np 

arr = np.arange(5) 
print("Array original: ", arr) 

constant = 5 
new_arr = arr + constant 
print("Array con la constante sumada: ", new_arr)

Array original:  [0 1 2 3 4]
Array con la constante sumada:  [5 6 7 8 9]


In [15]:
#4. Sume elemento a elemento los dos arrays utilizando el operador +

import numpy as np

array1 = np.arange(5)
array2 = np.arange(5,10)

suma_arrays = []

for i in range(len(array1)):
    suma_arrays.append(array1[i] + array2[i])

print(suma_arrays)

[5, 7, 9, 11, 13]


In [18]:
#5. Multiplique elemento a elemento los dos arrays utilizando el operador *

import numpy as np

array1 = np.arange(5)
array2 = np.arange(5,10)

print(array1)
print(array2)

resultado = array1 * array2
print(resultado)

[0 1 2 3 4]
[5 6 7 8 9]
[ 0  6 14 24 36]


## 6.3 Indexación 

En los arreglos podemos obtener elementos de ellos a partir de sus índices. Los índices de los arreglos tienen la siguiente sintaxis:

        array[a : b]
        
Este código significa que se obtendrá los elementos de {a} hasta b-1.


### 3. Realice las siguientes instrucciones:


In [2]:
#1. Crear un arreglo del 0 al 10 utilizando np.arange()
import numpy as np

arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
#2. Obtenga los primeros 3 elementos del arreglo
import numpy as np

arr = np.arange(0,11)
print(arr[:3])

[0 1 2]


In [4]:
#3. Obtenga los elementos del 2 al 4
import numpy as np

arr = np.arange(0,11)
print(arr[2:5])

[2 3 4]


In [7]:
#4. Ahora haga una copia de su arreglo asignándolo a otra variable, y utilice el método array.copy()

import numpy as np

arr = np.arange(0,11)
arr_copy = arr.copy()
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
#5. A la copia del arreglo asigne el número 20 a los tres primeros elementos del mismo.

import numpy as np

arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy[0:3] = [20, 20, 20]
print(arr_copy)

[20 20 20  3  4  5  6  7  8  9 10]


Si utilizamos matrices para obtener ciertos elementos utilizamos doble corchete:

        matriz[a][b]
        
Es posible formar matrices uniendo los arrays:

        matriz = (array1, array2, array3,...)

### 4. Ejecute las siguientes instrucciones:

In [1]:
#1. Crear 3 arreglos de 5 elementos utilizando np.arange

import numpy as np

arr1 = np.arange(5)
arr2 = np.arange(5, 10)
arr3 = np.arange(10, 15)

print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [3]:
#2. Formar la matriz con los tres arrays y obtenga las dimensiones de la matriz utilizando la función np.shape()

import numpy as np

arr1 = np.arange(5)
arr2 = np.arange(5, 10)
arr3 = np.arange(10, 15)

matriz = np.stack([arr1, arr2, arr3])
print(matriz)
print(np.shape(matriz))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [7]:
#3. Después obtenga el elemento (3,2) de la matriz
import numpy as np

arr1 = np.arange(5)
arr2 = np.arange(5, 10)
arr3 = np.arange(10, 15)

matriz = np.stack([arr1, arr2, arr3])
print(matriz[2][2])

12


## 6.4 Transponer matrices

Para transponer matrices utilizamos el método T que seguirá a un arreglo:

        array.T

### 5. Obtenga la transpuesta de la matriz del ejercicio anterior.

In [9]:
import numpy as np

arr1 = np.arange(5)
arr2 = np.arange(5, 10)
arr3 = np.arange(10, 15)

matriz = np.stack([arr1, arr2, arr3])

matriz_transpuesta = matriz.T

print(matriz_transpuesta)


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## 6.5 Algunas funciones con arrays

- Obtener la raíz cuadrada de cada elemento de un arreglo: np.sqrt(arreglo)
- Crear un arreglo que contenga n números aleatorios: np.random.rand(n)
- Calcular la exponencial de cada elemento de un arreglo: np.exp(arreglo)
- Obtener el logaritmo de cada elemento de un arreglo: np.log(arreglo)

### 6. Realice un código que utilice las cuatro funciones:


In [10]:
import numpy as np

# Metodo np.sqrt()
arreglo = np.array([1, 4, 9, 16])
raiz_cuadrada = np.sqrt(arreglo)
print(raiz_cuadrada)

# Metodo np.random.rand()
n = 10
arr = np.random.rand(n)
print(arr)

# Metodo np.exp()
arreglo = np.array([1, 2, 3, 4])
exponencial = np.exp(arreglo)
print(exponencial)

# Metodo np.log()
arreglo = np.array([1, 2, 3, 4])
logaritmo_arreglo = np.log(arreglo)
print(logaritmo_arreglo)


[1. 2. 3. 4.]
[0.1517463  0.28236791 0.4104067  0.55003127 0.58902606 0.65968636
 0.5698523  0.40060652 0.69174199 0.57518694]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


### 7. Ejercicio

Crear la funcion "pares" que devuelva un array o vector de números pares entre dos valores que serán parámetros de la función (inicio, fin)

Probar la función "pares" con los números 1 y 30
Probar la función "pares" con los números 2 y 40


In [11]:
def pares(inicio, fin):
    resultado = []
    for numero in range(inicio, fin + 1):
        if numero % 2 == 0:
            resultado.append(numero)

    return resultado


print(pares(1, 30))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [12]:
def pares(inicio, fin):
    resultado = []
    for numero in range(inicio, fin + 1):
        if numero % 2 == 0:
            resultado.append(numero)

    return resultado

print(pares(2, 40))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]
